kotlin.code.style=official

org.gradle.jvmargs=-Xmx1g -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=false
kotlin.native.ignoreDisabledTargets=true

GROUP=com.serranofp
# SONATYPE_HOST=CENTRAL_PORTAL
# RELEASE_SIGNING_ENABLED=true

POM_DESCRIPTION=Builder Lamba Kotlin plug-in
POM_URL=https://serranofp.com

POM_LICENSE_NAME=The Apache Software License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo

POM_DEVELOPER_ID=alejandro.serrano.mena
POM_DEVELOPER_NAME=Alejandro Serrano Mena
POM_DEVELOPER_URL=https://serranofp.com

POM_SCM_URL=https://github.com/serras/builder-lambda
POM_SCM_CONNECTION=scm:git:git://github.com/serras/builder-lambda.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/serras/builder-lambda.git

SONATYPE_CONNECT_TIMEOUT_SECONDS=600
SONATYPE_CLOSE_TIMEOUT_SECONDS=1800