on:
  pull_request: {}
  push:
    branches:
      - master
      - main

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

concurrency:
  group: pull_request-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v7

      - name: Cache Kotlin Native dependencies
        uses: actions/cache@v6
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/libs.versions.toml', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: 25

      - uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - run: ./gradlew build --continue

      - uses: mikepenz/action-junit-report@v6
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - run: ./test.sh
